frameworkVersion: '3'

service: my-workspace

configValidationMode: error

plugins:
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  deploymentMethod: direct
  disableRollback: false
# tracing:
# # Can only be true if API Gateway is inside a stack.
#   apiGateway: true
# # Optional, can be true (true equals 'Active'), 'Active' or 'PassThrough'
#   lambda: true
#   environment:
#   NODE_ENV: ${opt:stage, 'dev'}
#   versionFunctions: false

custom:
  serverless-offline:
  useChildProcesses: true
  httpPort: 3000
  websocketPort: 3001
  lambdaPort: 3002
  optimize:
  external: ['swagger-ui-dist']

package:
  patterns:
    - '!./**'
    - ./dist/apps/my-workspace/**
    - node_modules/**

functions:
  participants-app:
    handler: dist/apps/my-workspace/main.handler
    package:
      individually: false
    events: # HTTP API endpoint (API Gateway v2)
      - httpApi:
          method: any
          path: /my-workspace/{proxy+}
